Fix docutils warnings for updating to new crate-docs-theme
ERROR: "table" widths do not match the number of columns in table (5).

Apparently, a newer release of docutils is more strict, and bails out
when reading invalid markup.